import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import { Toaster } from "@/components/ui/sonner";


const poppins = Poppins({
  weight : ["100","200","300","500","400","700","800"],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
         <Toaster /> 
        <NextAuthSessionProvider>
        <Header/>
      <main className="container max-w-6xl mx-auto py-3 px-6 lg:px-8">
      {children}
      </main>
      </NextAuthSessionProvider>
      </body>
    </html>
  );
}
